name: Release DevOps with Docker # Name of the workflow

# Trigger the workflow on a push to the main branch
on:
  push:
    branches:
      - main

# Jobs definition
jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: benjaminsuljic82/express-app:latest

  deploy-to-vps:
    name: Deploy to Contabo VPS
    runs-on: ubuntu-latest
    needs: publish-docker-hub
    steps:
      # Setup SSH agent
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY_CONTABO }}

      # Deploy the container to VPS
      - name: Deploy Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no root@75.119.156.74 << 'EOF'
            # Pull the latest Docker image
            docker pull benjaminsuljic82/express-app:latest

            # Stop the existing container
            docker stop express-app || true
            docker rm express-app || true

            # Run the updated container
            docker run -d \
              --name express-app \
              -p 8080:8080 \
              benjaminsuljic82/express-app:latest
          EOF
